### ISSUE TITLE
The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by cwiese** [JuliaComputing/Azure.jl#25]
Updated to 0.4.0 from 0.3.1 and suddenly "putBlob" is failing 
```
: put
│   req.headers =
│    Dict{String, String} with 5 entries:
│      "Content-Length" => "18655362"
│      "x-ms-date"      => "Tue, 09 Nov 2021 22:22:44 GMT"
│      "x-ms-blob-type" => "BlockBlob"
│      "Authorization"  => "SharedKey accountname:k20HfZ6vl4Y9IwJFDa6wWf+09Da/dHf4o3mgZuCikII="
└      "x-ms-version"   => "2016-05-31"
┌ Warning: Storage service request failed
│   resp = Downloads.Response("https", "https://accountname.blob.core.windows.net/simulation/model/TES/site1/0.5.2/scenario_1_618af498c759887e902d4352.jld2", 400, "HTTP/1.1 400 The value for one of the HTTP headers is not in the correct format", ["content-length" => "322", "content-type" => "application/xml", "server" => "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id" => "4b8744b0-701e-0036-21b8-d51a16000000", "x-ms-version" => "2016-05-31", "date" => "Tue, 09 Nov 2021 22:22:45 GMT"])
│   retry = false
└ @ Azure.REST ~/.julia/packages/Azure/hmLrR/src/rest_api_protocol.jl:161
```

**Comment by tanmaykm** [comment]
In 0.4.0, we have switched to using Downloads.jl as the HTTP client instead of HTTP.jl. This issue happens because Downloads.jl 
 is not able to determine the content length when an `IO` instance is provided to upload data from, and switches to using a chunked transfer encoding. And the `putBlob` Azure API endpoint does not support chunked transfers.

The solution is to not use chunked transfers for `putBlob`. This [PR to Downloads.jl](https://github.com/JuliaLang/Downloads.jl/pull/167) would let it also look into the `content-length` header that we supply to determine the data size to expect in the `IO` instance we pass.

**Comment by tanmaykm** [comment]
But until the Downloads.jl PR is merged (and backported), we may need some workaround in Azure.jl. We could treat file handles differently and see if we can pass it in a form that Downloads.jl can determine size from.
